# Generated by Django 5.2.8 on 2025-11-07 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('commerciale_riferimento', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('tempo_risposta_ore', models.IntegerField(help_text='Tempo di risposta in ore')),
                ('tempo_risoluzione_ore', models.IntegerField(help_text='Tempo di risoluzione in ore')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLA',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(max_length=100, unique=True)),
                ('data_ordine', models.DateField()),
                ('tipo_ordine', models.CharField(choices=[('STANDARD', 'Ordine Standard'), ('RMA', 'RMA'), ('RINNOVO_GARANZIA', 'Rinnovo Garanzia')], default='STANDARD', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='orders.fornitore')),
                ('ordine_materiale_collegato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_estensione_garanzia', to='orders.ordine')),
                ('ordine_originale_rma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_rma', to='orders.ordine')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='ArticoloOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('numero_seriale', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('quantita', models.IntegerField(default=1)),
                ('mesi_garanzia', models.IntegerField(default=12, help_text='Mesi di garanzia')),
                ('data_scadenza_garanzia', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='orders.ordine')),
            ],
            options={
                'verbose_name': 'Articolo Ordine',
                'verbose_name_plural': 'Articoli Ordini',
                'ordering': ['-ordine__data_ordine', 'articolo'],
            },
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rma', models.CharField(max_length=100, unique=True)),
                ('data_apertura', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('stato', models.CharField(choices=[('APERTO', 'Aperto'), ('IN_LAVORAZIONE', 'In Lavorazione'), ('CHIUSO', 'Chiuso'), ('ANNULLATO', 'Annullato')], default='APERTO', max_length=20)),
                ('override_garanzia', models.BooleanField(default=False, help_text='Forza apertura RMA anche se fuori garanzia')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articolo_originale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_aperti', to='orders.articoloordine')),
                ('ordine_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma', to='orders.ordine')),
            ],
            options={
                'verbose_name': 'RMA',
                'verbose_name_plural': 'RMA',
                'ordering': ['-data_apertura'],
            },
        ),
        migrations.CreateModel(
            name='SedeCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sede', models.CharField(max_length=200)),
                ('indirizzo', models.TextField()),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedi', to='orders.cliente')),
            ],
            options={
                'verbose_name': 'Sede Cliente',
                'verbose_name_plural': 'Sedi Clienti',
                'ordering': ['cliente__nome', 'nome_sede'],
            },
        ),
        migrations.AddField(
            model_name='articoloordine',
            name='sede_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='orders.sedecliente'),
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contratto', models.CharField(max_length=100, unique=True)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='orders.cliente')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='orders.sla')),
            ],
            options={
                'verbose_name': 'Service Contract',
                'verbose_name_plural': 'Service Contracts',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='RinnovoServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rinnovo', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('contract_nuovo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rinnovo_di', to='orders.servicecontract')),
                ('contract_originale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rinnovi', to='orders.servicecontract')),
            ],
            options={
                'verbose_name': 'Rinnovo Service Contract',
                'verbose_name_plural': 'Rinnovi Service Contracts',
            },
        ),
        migrations.AddField(
            model_name='articoloordine',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='orders.servicecontract'),
        ),
    ]
