# Generated by Django 5.2.8 on 2025-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='tempo_risoluzione_ore',
        ),
        migrations.AddField(
            model_name='sla',
            name='disponibilita_copertura',
            field=models.CharField(choices=[('8X5', '8x5 (Lun-Ven, 8:00-18:00)'), ('9X5', '9x5 (Lun-Ven, 8:00-17:00)'), ('12X5', '12x5 (Lun-Ven, 8:00-20:00)'), ('24X7', '24x7 (24 ore su 24, 7 giorni su 7)'), ('NBD', 'NBD (Next Business Day)')], default='8X5', help_text='Disponibilità della copertura', max_length=10),
        ),
        migrations.AddField(
            model_name='sla',
            name='tipo_intervento',
            field=models.CharField(choices=[('SOLO_MATERIALE', 'Solo Materiale'), ('ON_SITE', 'Intervento On-Site'), ('REMOTO', 'Intervento Remoto'), ('ON_SITE_REMOTO', 'On-Site + Remoto')], default='SOLO_MATERIALE', help_text='Tipo di intervento previsto', max_length=20),
        ),
    ]
