# Generated by Django 5.2.8 on 2025-11-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_sla_tempo_risoluzione_ore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='tempo_risposta_ore',
        ),
        migrations.AddField(
            model_name='sla',
            name='tempo_risposta',
            field=models.CharField(choices=[('1H', '1 ora'), ('2H', '2 ore'), ('4H', '4 ore'), ('8H', '8 ore'), ('24H', '24 ore'), ('NBD', 'NBD (Next Business Day)')], default='8H', help_text='Tempo di risposta', max_length=10),
        ),
    ]
