# Generated by Django 5.2.8 on 2025-11-07 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_sla_tempo_risposta_ore_sla_tempo_risposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_articolo', models.CharField(max_length=100, unique=True, verbose_name='Codice Articolo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Articolo')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('costruttore', models.CharField(blank=True, max_length=100, verbose_name='Costruttore')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['codice_articolo'],
            },
        ),
        migrations.RemoveField(
            model_name='articoloordine',
            name='descrizione',
        ),
        migrations.AddField(
            model_name='articoloordine',
            name='note',
            field=models.TextField(blank=True, help_text="Note personalizzate per questo articolo nell'ordine", verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='articoloordine',
            name='numero_seriale',
            field=models.CharField(blank=True, help_text='Numero seriale univoco (se presente, quantità = 1)', max_length=200, null=True, unique=True, verbose_name='Numero Seriale'),
        ),
        migrations.AlterField(
            model_name='articoloordine',
            name='quantita',
            field=models.IntegerField(default=1, verbose_name='Quantità'),
        ),
        migrations.AlterField(
            model_name='articoloordine',
            name='articolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='orders.articolo', verbose_name='Articolo'),
        ),
    ]
