# Generated by Django 5.2.8 on 2025-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_articolo_remove_articoloordine_descrizione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='mesi_garanzia_default',
            field=models.IntegerField(default=12, help_text='Mesi di garanzia di default per gli articoli di questo ordine', verbose_name='Garanzia Default (mesi)'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='pdf_ordine',
            field=models.FileField(blank=True, help_text="Upload del documento PDF dell'ordine", null=True, upload_to='ordini_pdf/', verbose_name='PDF Ordine'),
        ),
        migrations.AlterField(
            model_name='sedecliente',
            name='indirizzo',
            field=models.TextField(blank=True),
        ),
    ]
