# Generated by Django 5.2.8 on 2025-11-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordine_mesi_garanzia_default_ordine_pdf_ordine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='nome',
        ),
        migrations.AddField(
            model_name='ordine',
            name='numero_offerta',
            field=models.CharField(blank=True, help_text='Numero offerta di riferimento', max_length=100, verbose_name='Numero Offerta'),
        ),
        migrations.CreateModel(
            name='RichiestaOfferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_richiesta', models.CharField(max_length=100, unique=True, verbose_name='Numero Richiesta')),
                ('tipo_richiesta', models.CharField(choices=[('MATERIALE', 'Materiale/Prodotti'), ('RINNOVO_GARANZIA', 'Rinnovo Garanzia'), ('SERVICE_CONTRACT', 'Service Contract')], default='MATERIALE', max_length=20)),
                ('richiesta_testuale', models.TextField(help_text='Descrizione testuale della richiesta', verbose_name='Richiesta del Cliente')),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('IN_LAVORAZIONE', 'In Lavorazione'), ('INVIATA', 'Inviata al Cliente'), ('APPROVATA', 'Approvata'), ('RIFIUTATA', 'Rifiutata'), ('CONVERTITA', 'Convertita in Ordine')], default='BOZZA', max_length=20)),
                ('scadenza_attuale', models.DateField(blank=True, null=True, verbose_name='Scadenza Attuale')),
                ('note', models.TextField(blank=True)),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='richieste_offerta', to='orders.cliente')),
                ('commerciale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_offerta', to=settings.AUTH_USER_MODEL)),
                ('ordine_convertito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richiesta_origine', to='orders.ordine', verbose_name='Ordine Convertito')),
            ],
            options={
                'verbose_name': 'Richiesta Offerta',
                'verbose_name_plural': 'Richieste Offerta',
                'ordering': ['-data_richiesta'],
            },
        ),
        migrations.CreateModel(
            name='RigaOfferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500, verbose_name='Descrizione')),
                ('quantita', models.IntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Unitario €')),
                ('mesi_durata', models.IntegerField(blank=True, null=True, verbose_name='Mesi Durata')),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.articolo')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='orders.richiestaofferta')),
            ],
            options={
                'verbose_name': 'Riga Offerta',
                'verbose_name_plural': 'Righe Offerta',
            },
        ),
    ]
