# Generated by Django 5.2.8 on 2025-11-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordine_sede_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='numero_offerta',
        ),
        migrations.AddField(
            model_name='ordine',
            name='richiesta_offerta',
            field=models.ForeignKey(blank=True, help_text='Seleziona offerta approvata', limit_choices_to={'stato__in': ['APPROVATA', 'CONVERTITA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.richiestaofferta', verbose_name='Offerta di Riferimento'),
        ),
        migrations.AlterField(
            model_name='richiestaofferta',
            name='numero_richiesta',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Numero Richiesta'),
        ),
    ]
