# Generated by Django 5.2.8 on 2025-11-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_ordine_numero_offerta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='sede_default',
            field=models.ForeignKey(help_text='⚠️ OBBLIGATORIO: Sede cliente di default per gli articoli di questo ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sedecliente', verbose_name='Sede Default'),
        ),
    ]
