# Generated by Django 5.2.8 on 2025-11-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_ordine_sede_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='sede_default',
            field=models.ForeignKey(blank=True, help_text="⚠️ OBBLIGATORIO per ordini Standard. Per RMA/Rinnovo viene ereditato dall'ordine di riferimento.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sedecliente', verbose_name='Sede Default'),
        ),
    ]
